FROM node:alpine
ARG DB_HOST
ARG DB_PORT
ARG PORT

ARG ITEM_BACKEND_WS
ARG NAMESPACE_BACKEND_WS
ARG AUTH_BACKEND_WS

ARG GRAPHQL_URLS

ARG GRAPHIQL_PROTOCOL

ARG SCHEMA_REFRESH_INTERVAL

ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT

ENV PORT=$PORT

ENV ITEM_BACKEND_WS=$ITEM_BACKEND_WS
ENV NAMESPACE_BACKEND_WS=$NAMESPACE_BACKEND_WS
ENV AUTH_BACKEND_WS=$AUTH_BACKEND_WS

ENV GRAPHQL_URLS=$GRAPHQL_URLS

ENV GRAPHIQL_PROTOCOL=$GRAPHIQL_PROTOCOL

ENV SCHEMA_REFRESH_INTERVAL=$SCHEMA_REFRESH_INTERVAL

EXPOSE $PORT

RUN npm set registry https://npm-registry.dukfaar.com

COPY package*.json ./
RUN npm install --production

COPY tsconfig.json ./
COPY src ./src 
RUN npm run-script tsc

CMD ["node", "dist/"]